Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,41 +13,54 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+ 
       - name: Checkout code
         uses: actions/checkout@v3
+
 
       - name: Setup Node.js
         uses: actions/setup-node@v3
         with:
           node-version: 20
 
+   
       - name: Install dependencies
         run: npm install
+
 
       - name: Build application
         run: npm run build
 
-      
+ 
       - name: Check project structure
         run: ls -la
 
-     
+      
       - name: Check .next folder
-        run: ls -la .next
+        run: ls -la .next || echo ".next folder not found!"
 
   deploy:
     runs-on: ubuntu-latest
     needs: build
 
     steps:
+     
       - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Deploy to server
+      
+      - name: Setup SSH
         run: |
           mkdir -p ~/.ssh
           echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
           ssh-keyscan -H 5.144.131.250 >> ~/.ssh/known_hosts
-          ssh -i ~/.ssh/id_rsa sunflowe@5.144.131.250 "echo Connected!"
-          rsync -avz ./build/ sunflowe@5.144.131.250:~/project
+
+     
+      - name: Test SSH connection
+        run: ssh -i ~/.ssh/id_rsa sunflowe@5.144.131.250 "echo Connected!"
+
+   
+      - name: Deploy to server
+        run: |
+          rsync -avz .next/ sunflowe@5.144.131.250:~/project/.next/
